apiVersion: apps/v1
kind: Deployment
metadata:
  name: jb-dpmt
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 10
  template:
    metadata:
      name: nginx-2
      labels: 
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx
        image: nginx    
        ports:
          - containerPort: 80
