apiVersion: v1
kind: Service
metadata:
  name: jb-svc
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30004
  selector:
    app: myapp   
    type: front-end   
