containerPlataform: a
replicaCount: 1 
appName: ""
namespace: ""

productionReplicaCount: 1

readinessProbe:
  httpGet:
    path: /health
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 20
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 6

resources:
  limits:
    cpu: 500m
    memory: 256Mi

image:
  repository: a
  tag: latest
  pullPolicy: IfNotPresent
  ports:
    - name: http
      containerPort: 3000
      protocol: TCP

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: ""