apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset1
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: meupod2
      labels:
        app: nginx
    spec:
      containers:
      - name: site
        image: kubedevio/nginx-color:green
        ports:
         - containerPort: 80  
  replicas: 6  
  
