apiVersion: apps/v1
kind: Deployment
metadata:
  name: jb-dpmt
  labels:
    tier: frontend
    app: nginx
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      name: nginx-2
      labels: 
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx    
        ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: jb-svc
spec:
  selector:
    app: myapp
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30000
  type: NodePort
